### ISSUE TITLE
NameError: global name 'array_ids' is not defined

### ISSUE THREAD

**Issue by TheaDene** [benmaier/qsuite#15]
```
$ qsuite submit err 
Connected to server
Fetching array IDs that produced errors with keywords ERR
ssh> for i in `seq 0 44999`; do cat /home/user/fixpkt_ana/fixpkt_ana__rk45_1.0_NMEAS_50_ONLYSAVETIME_False/output/progress_$i; done;
Traceback (most recent call last):
  File "/anaconda/bin/qsuite", line 11, in <module>
    load_entry_point('qsuite==0.4.4', 'console_scripts', 'qsuite')()
  File "/anaconda/lib/python2.7/site-packages/qsuite-0.4.4-py2.7.egg/qsuite/qsuite_binary.py", line 411, in main
    if len(array_ids)>0:
```

**Comment by benmaier** [comment]
pls update
